import matplotlib.pyplot as plt
import pandas as pd

def plot_data(data):
    """ fig = plt.figure(figsize = (18,6))
    ax1 = fig.add_subplot(2,2,1) 
    ax1.set_title('Who survived with respect to the gender?')  
    ax2 = fig.add_subplot(2,2,2)    
    data.Pclass[data.Survived == 1].value_counts().plot(kind='barh')
    ax2.set_title('Survived by Class')
    ax2.set_xlabel('Class')
    ax3 = fig.add_subplot(2,2,3)    
    data.Pclass.value_counts().plot(kind='bar',title='Distribution of Classes')
    ax3.set_xlabel('Class')
    ax4 = fig.add_subplot(2,2,4)    
    data.Age[data.Survived == 1].value_counts().plot(kind='kde')
    data.Age[data.Survived == 0].value_counts().plot(kind='kde')    
    ax4.set_title('Survived by Age')
    ax4.set_xlabel('Age')
    ax4.legend(('Survived', 'Dead'), loc='best')
    death_count = pd.crosstab([data.Pclass, data.Sex],data.Survived.astype(bool))
    death_count.plot(kind='bar',stacked=True,color=['red','yellow'], grid=False, title='Class&Sex by Survivorship')
    death_count = pd.crosstab([data.Sex],data.Survived.astype(bool))
    death_count.plot(kind='bar',stacked=True,color=['red','yellow'], grid=False, title='Sex by Survivorship') """
    fig = plt.figure(figsize = (18,6))
    ax1 = fig.add_subplot(2,2,1)    
    data.Survived[(data.Sex == 'female') & (data.Pclass == 3)].value_counts().plot(kind='bar', color = 'red', title = 'Who Survived respect to gender and class?', label ='Female Low CLass', legend=True)
    ax1.set_xticklabels(['Survived','Dead'],rotation=0)
    ax1.set_ylim(0,data[data.Sex == 'female'].shape[0])
#    ax1.set_xlim(-1, data.shape[0])
    ax2 = fig.add_subplot(2,2,2)    
    data.Survived[(data.Sex == 'male') & (data.Pclass == 3)].value_counts().plot(kind='bar', color = 'gold', title = 'Who Survived respect to gender and class?', label ='Male Low Class', legend=True)
    ax2.set_xticklabels(['Survived','Dead'], rotation=0)
    ax2.set_ylim(0,data[data.Sex == 'male'].shape[0])
    ax3 = fig.add_subplot(2,2,3)    
    data.Survived[(data.Sex == 'female') & data.Pclass.isin([1,2])].value_counts().plot(kind='bar', color = 'red', title = 'Who Survived respect to gender and class?', label ='Female High Class', legend=True)
    ax3.set_xticklabels(['Survived','Dead'],rotation=0)
    ax3.set_ylim(0,data[data.Sex == 'female'].shape[0])
    ax4 = fig.add_subplot(2,2,4)    
    data.Survived[(data.Sex == 'male') & data.Pclass.isin([1,2])].value_counts().plot(kind='bar', color = 'red', title = 'Who Survived respect to gender and class?', label ='Male High Class', legend=True)
    ax4.set_xticklabels(['Survived','Dead'],rotation=0)
    ax4.set_ylim(0,data[data.Sex == 'male'].shape[0])